# Generated by Django 4.1.7 on 2023-05-13 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lostchildren", "0004_rename_reports_matchingreports_reports"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchNotification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_seen", models.BooleanField(default=False)),
                ("is_opened", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(blank=True, default="match_found", max_length=100),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lost_child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="lostchildren.lostchild",
                    ),
                ),
                (
                    "matching_child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="lostchildren.matchingchild",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
