# Generated by Django 4.1.7 on 2023-05-17 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notification_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgVerifyNotification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_seen", models.BooleanField(default=False)),
                ("is_opened", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("verification_request", "Verification Request"),
                            ("verification_success", "Verification Success"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "org_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_user_verify_nofication",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_verify_nofication",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
