# Generated by Django 4.1.7 on 2023-05-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification_app", "0002_matchnotification_delete_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchnotification",
            old_name="recieved_child",
            new_name="matching_child",
        ),
    ]
