# Generated by Django 4.1.7 on 2023-05-14 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lostchildren", "0004_rename_reports_matchingreports_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchingchild",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="matchingreports",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
