# Generated by Django 4.1.7 on 2023-05-14 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lostchildren", "0004_rename_reports_matchingreports_reports"),
        ("notification_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchnotification",
            name="lost_child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_notification",
                to="lostchildren.lostchild",
            ),
        ),
        migrations.AlterField(
            model_name="matchnotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_notification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DropChildNotification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_seen", models.BooleanField(default=False)),
                ("is_opened", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("drop_child_request", "Drop Child Request"),
                            ("drop_child_success", "Drop Child Success"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "found_child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_notification",
                        to="lostchildren.foundchild",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_notification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
