# Generated by Django 4.1.7 on 2023-04-30 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lostchildren.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LostChild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("child_name", models.CharField(blank=True, max_length=50, null=True)),
                ("father_name", models.CharField(blank=True, max_length=50, null=True)),
                ("mother_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date_of_lost", models.DateField(blank=True, null=True)),
                (
                    "location_where_lost",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AJK", "Azad Jammu and Kashmir"),
                            ("Bal", "Balochistan"),
                            ("GB", "Gilgit Baltistan"),
                            ("KP", "Khyber Pakhtunkhwa"),
                            ("Pun", "Punjab"),
                            ("Snd", "Sindh"),
                        ],
                        max_length=18,
                        null=True,
                    ),
                ),
                (
                    "home_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lostchildren.models.get_child_image_upload_path_lost_child,
                    ),
                ),
                ("image_encoding", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lost", "Lost"),
                            ("found", "Found"),
                            ("received", "Received"),
                            ("resolved", "Resolved"),
                        ],
                        default="lost",
                        max_length=20,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lostReport",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FoundChild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("child_name", models.CharField(blank=True, max_length=50, null=True)),
                ("father_name", models.CharField(blank=True, max_length=50, null=True)),
                ("mother_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date_of_found", models.DateField(blank=True, null=True)),
                (
                    "location_where_found",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lostchildren.models.get_child_image_upload_path_found_child,
                    ),
                ),
                ("image_encoding", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lost", "Lost"),
                            ("found", "Found"),
                            ("received", "Received"),
                            ("resolved", "Resolved"),
                        ],
                        default="found",
                        max_length=20,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foundReport",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
