# Generated by Django 4.1.7 on 2023-07-02 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lostchildren.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("child_name", models.CharField(blank=True, max_length=50, null=True)),
                ("father_name", models.CharField(blank=True, max_length=50, null=True)),
                ("mother_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AJK", "Azad Jammu and Kashmir"),
                            ("Bal", "Balochistan"),
                            ("GB", "Gilgit Baltistan"),
                            ("KP", "Khyber Pakhtunkhwa"),
                            ("Pun", "Punjab"),
                            ("Snd", "Sindh"),
                        ],
                        max_length=18,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "home_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lostchildren.models.get_child_image_upload_path,
                    ),
                ),
                ("image_encoding", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lost", "Lost"),
                            ("found", "Found"),
                            ("received", "Received"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoundChild",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lostchildren.report",),
        ),
        migrations.CreateModel(
            name="LostChild",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lostchildren.report",),
        ),
        migrations.CreateModel(
            name="ReceivedChild",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lostchildren.report",),
        ),
        migrations.CreateModel(
            name="MatchingChild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("distance", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lost_child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_child",
                        to="lostchildren.lostchild",
                    ),
                ),
                (
                    "recieved_child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match",
                        to="lostchildren.receivedchild",
                    ),
                ),
            ],
        ),
    ]
