# Generated by Django 4.1.7 on 2023-04-28 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lostchildren", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foundchild",
            old_name="image2",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="foundchild",
            old_name="image_encoding1",
            new_name="image_encoding",
        ),
        migrations.RenameField(
            model_name="lostchild",
            old_name="image2",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="lostchild",
            old_name="image_encoding1",
            new_name="image_encoding",
        ),
        migrations.RemoveField(
            model_name="foundchild",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="foundchild",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="foundchild",
            name="image_encoding2",
        ),
        migrations.RemoveField(
            model_name="foundchild",
            name="image_encoding3",
        ),
        migrations.RemoveField(
            model_name="lostchild",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="lostchild",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="lostchild",
            name="image_encoding2",
        ),
        migrations.RemoveField(
            model_name="lostchild",
            name="image_encoding3",
        ),
    ]
