# Generated by Django 4.1.7 on 2023-03-29 15:10

from django.db import migrations, models
import lostchildren.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lostchildren", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundChild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("father_name", models.CharField(max_length=50)),
                ("mother_name", models.CharField(max_length=50)),
                (
                    "image1",
                    models.ImageField(
                        upload_to=lostchildren.models.get_child_image_upload_path_found_child
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        upload_to=lostchildren.models.get_child_image_upload_path_found_child,
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        upload_to=lostchildren.models.get_child_image_upload_path_found_child,
                    ),
                ),
                ("image_encoding1", models.JSONField(blank=True, null=True)),
                ("image_encoding2", models.JSONField(blank=True, null=True)),
                ("image_encoding3", models.JSONField(blank=True, null=True)),
                ("date_of_lost", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_of_found", models.DateField(blank=True, null=True)),
                (
                    "found_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
