# Generated by Django 4.1.7 on 2023-05-10 06:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lostchildren", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchingChild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("distance", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recieved_child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match",
                        to="lostchildren.foundchild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchingReports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reports",
                    models.ManyToManyField(
                        related_name="matches", to="lostchildren.matchingchild"
                    ),
                ),
                (
                    "lost_child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchingReports",
                        to="lostchildren.lostchild",
                    ),
                ),
            ],
        ),
    ]
