# Generated by Django 4.1.7 on 2023-05-20 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lostchildren", "0002_matchingchild_matchingreports"),
    ]

    operations = [
        migrations.AddField(
            model_name="foundchild",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="foundchild",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lostchild",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lostchild",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
