# Generated by Django 4.1.7 on 2023-04-02 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lostchildren", "0002_foundchild"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FoundChild",
        ),
    ]
