# Generated by Django 4.1.7 on 2023-05-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lostchildren", "0002_matchingchild_matchingreports"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchingchild",
            old_name="recievedChild",
            new_name="recieved_child",
        ),
    ]
