# Generated by Django 4.1.7 on 2023-04-02 11:55

from django.db import migrations, models
import lostchildren.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lostchildren", "0004_rename_location_lostchild_location_where_lost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundChild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("father_name", models.CharField(max_length=50)),
                ("mother_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("phone_number", models.CharField(max_length=11, null=True)),
                ("location_where_found", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50, null=True)),
                ("province", models.CharField(max_length=50, null=True)),
                ("home_address", models.CharField(max_length=100, null=True)),
                ("date_of_lost", models.DateField()),
                ("description", models.TextField()),
                (
                    "image1",
                    models.ImageField(
                        upload_to=lostchildren.models.get_child_image_upload_path_found_child
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        upload_to=lostchildren.models.get_child_image_upload_path_found_child,
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        upload_to=lostchildren.models.get_child_image_upload_path_found_child,
                    ),
                ),
                ("image_encoding1", models.JSONField(blank=True, null=True)),
                ("image_encoding2", models.JSONField(blank=True, null=True)),
                ("image_encoding3", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
