# Generated by Django 4.1.7 on 2023-04-02 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("lostchildren", "0007_alter_lostchild_province"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foundchild",
            old_name="first_name",
            new_name="child_name",
        ),
        migrations.RenameField(
            model_name="lostchild",
            old_name="first_name",
            new_name="child_name",
        ),
        migrations.RemoveField(
            model_name="foundchild",
            name="city",
        ),
        migrations.RemoveField(
            model_name="foundchild",
            name="date_of_lost",
        ),
        migrations.RemoveField(
            model_name="foundchild",
            name="home_address",
        ),
        migrations.RemoveField(
            model_name="foundchild",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="foundchild",
            name="province",
        ),
        migrations.RemoveField(
            model_name="lostchild",
            name="last_name",
        ),
        migrations.AddField(
            model_name="foundchild",
            name="date_of_found",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="foundchild",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="lostchild",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="foundchild",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="lostchild",
            name="date_of_lost",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="lostchild",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
