# Generated by Django 4.1.7 on 2023-04-02 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lostchildren", "0008_rename_first_name_foundchild_child_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foundchild",
            name="date_of_found",
            field=models.DateField(default=datetime.date(2023, 4, 2)),
        ),
        migrations.AlterField(
            model_name="lostchild",
            name="date_of_lost",
            field=models.DateField(default=datetime.date(2023, 4, 2)),
        ),
    ]
