# Generated by Django 4.1.7 on 2023-07-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuserprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="appuserprofile",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AJK", "Azad Jammu and Kashmir"),
                    ("Bal", "Balochistan"),
                    ("GB", "Gilgit Baltistan"),
                    ("KP", "Khyber Pakhtunkhwa"),
                    ("Pun", "Punjab"),
                    ("Snd", "Sindh"),
                ],
                max_length=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agencyprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="agencyprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=32, null=True
            ),
        ),
    ]
