# Generated by Django 4.1.7 on 2023-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0002_orgdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgdetails",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orgdetails",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orgdetails",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orgdetails",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
